import { z } from 'zod';

export const Skill = z.enum([
  'Attack',
  'Strength',
  'Defence',
  'Ranged',
  'Prayer',
  'Magic',
  'Runecraft',
  'Hitpoints',
  'Crafting',
  'Mining',
  'Smithing',
  'Fishing',
  'Cooking',
  'Firemaking',
  'Woodcutting',
  'Agility',
  'Herblore',
  'Thieving',
  'Fletching',
  'Slayer',
  'Farming',
  'Construction',
  'Hunter',
]);

export type Skill = z.infer<typeof Skill>;

export const Quest = z.enum([
  'A Kingdom Divided',
  'A Night at the Theatre',
  'A Porcine of Interest',
  "A Soul's Bane",
  'A Tail of Two Cats',
  'A Taste of Hope',
  'Animal Magnetism',
  'Another Slice of H.A.M.',
  'At First Light',
  'Below Ice Mountain',
  'Beneath Cursed Sands',
  'Between a Rock...',
  'Bone Voyage',
  'Children of the Sun',
  'Client of Kourend',
  'Cold War',
  'Contact!',
  'Creature of Fenkenstrain',
  'Darkness of Hallowvale',
  'Death on the Isle',
  'Death to the Dorgeshuun',
  'Defender of Varrock',
  'Demon Slayer',
  'Desert Treasure I',
  'Desert Treasure II - The Fallen Empire',
  'Devious Minds',
  'Dragon Slayer II',
  'Dream Mentor',
  "Eagles' Peak",
  'Elemental Workshop I',
  'Elemental Workshop II',
  "Enakhra's Lament",
  'Enlightened Journey',
  'Ethically Acquired Antiquities',
  'Fairytale I - Growing Pains',
  'Fairytale II - Cure a Queen',
  'Forgettable Tale...',
  'Garden of Tranquillity',
  'Getting Ahead',
  'Ghosts Ahoy',
  'Goblin Diplomacy',
  'Grim Tales',
  'Horror from the Deep',
  "Icthlarin's Little Helper",
  'In Aid of the Myreque',
  "King's Ransom",
  'Land of the Goblins',
  'Lunar Diplomacy',
  'Making Friends with My Arm',
  'Making History',
  'Meat and Greet',
  'Misthalin Mystery',
  'Monkey Madness II',
  'Mountain Daughter',
  "Mourning's End Part II",
  "My Arm's Big Adventure",
  "Olaf's Quest",
  'Perilous Moons',
  'Ratcatchers',
  'Recipe for Disaster',
  "Recipe for Disaster - Another Cook's Quest",
  'Recipe for Disaster - Culinaromancer',
  'Recipe for Disaster - Evil Dave',
  'Recipe for Disaster - King Awowogei',
  'Recipe for Disaster - Lumbridge Guide',
  'Recipe for Disaster - Mountain Dwarf',
  'Recipe for Disaster - Pirate Pete',
  'Recipe for Disaster - Sir Amik Varze',
  'Recipe for Disaster - Skrach Uglogwee',
  'Recipe for Disaster - Wartface & Bentnoze',
  'Recruitment Drive',
  'Royal Trouble',
  'Secrets of the North',
  'Shadow of the Storm',
  'Shield of Arrav',
  'Sins of the Father',
  'Sleeping Giants',
  'Song of the Elves',
  'Spirits of the Elid',
  'Swan Song',
  'Tale of the Righteous',
  'Tears of Guthix',
  'Temple of the Eye',
  'The Ascent of Arceuus',
  'The Corsair Curse',
  'The Depths of Despair',
  'The Eyes of Glouphrie',
  'The Feud',
  'The Forsaken Tower',
  'The Fremennik Exiles',
  'The Fremennik Isles',
  'The Garden of Death',
  'The Giant Dwarf',
  'The Golem',
  'The Hand in the Sand',
  'The Heart of Darkness',
  'The Lost Tribe',
  'The Path of Glouphrie',
  'The Queen of Thieves',
  'The Ribbiting Tale of a Lily Pad Labour Dispute',
  'The Slug Menace',
  'Tower of Life',
  "Twilight's Promise",
  'Wanted!',
  'What Lies Below',
  'While Guthix Sleeps',
  'X Marks the Spot',
  'Zogre Flesh Eaters',
  'Big Chompy Bird Hunting',
  'Biohazard',
  "Black Knights' Fortress",
  'Cabin Fever',
  'Clock Tower',
  "Cook's Assistant",
  'Death Plateau',
  "Doric's Quest",
  'Dragon Slayer I',
  'Druidic Ritual',
  'Dwarf Cannon',
  "Eadgar's Ruse",
  'Ernest the Chicken',
  'Family Crest',
  'Fight Arena',
  'Fishing Contest',
  "Gertrude's Cat",
  'Haunted Mine',
  'Hazeel Cult',
  "Heroes' Quest",
  'Holy Grail',
  'Imp Catcher',
  'In Search of the Myreque',
  'Jungle Potion',
  "Legends' Quest",
  'Lost City',
  "Merlin's Crystal",
  "Monk's Friend",
  'Monkey Madness I',
  "Mourning's End Part I",
  'Murder Mystery',
  'Nature Spirit',
  'Observatory Quest',
  'One Small Favour',
  "Pirate's Treasure",
  'Plague City',
  'Priest in Peril',
  'Prince Ali Rescue',
  'Rag and Bone Man I',
  'Rag and Bone Man II',
  'Regicide',
  'Romeo & Juliet',
  'Roving Elves',
  'Rum Deal',
  'Rune Mysteries',
  'Scorpion Catcher',
  'Sea Slug',
  "Shades of Mort'ton",
  'Sheep Herder',
  'Sheep Shearer',
  'Shilo Village',
  'Tai Bwo Wannai Trio',
  'Temple of Ikov',
  'The Dig Site',
  'The Fremennik Trials',
  'The Grand Tree',
  'The Great Brain Robbery',
  "The Knight's Sword",
  'The Restless Ghost',
  'The Tourist Trap',
  'Throne of Miscellania',
  'Tree Gnome Village',
  'Tribal Totem',
  'Troll Romance',
  'Troll Stronghold',
  'Underground Pass',
  'Vampyre Slayer',
  'Watchtower',
  'Waterfall Quest',
  "Witch's House",
  "Witch's Potion",
]);

export type Quest = z.infer<typeof Quest>;

export const MiniQuest = z.enum([
  "Alfred Grimhand's Barcrawl",
  'Barbarian Training',
  'Bear Your Soul',
  'Curse of the Empty Lord',
  "Daddy's Home",
  'The Enchanted Key',
  'Enter the Abyss',
  'Family Pest',
  'The Frozen Door',
  "The General's Shadow",
  'His Faithful Servants',
  "Hopespear's Will",
  'In Search of Knowledge',
  'Into the Tombs',
  'Lair of Tarn Razorlor',
  'Mage Arena I',
  'Mage Arena II',
  'Skippy and the Mogres',
]);

export type MiniQuest = z.infer<typeof MiniQuest>;

export const DiaryLocation = z.enum([
  'Ardougne',
  'Desert',
  'Falador',
  'Fremennik',
  'Kandarin',
  'Karamja',
  'Kourend & Kebos',
  'Lumbridge & Draynor',
  'Morytania',
  'Varrock',
  'Western Provinces',
  'Wilderness',
]);

export type DiaryLocation = z.infer<typeof DiaryLocation>;

export const DiaryTier = z.enum(['None', 'Easy', 'Medium', 'Hard', 'Elite']);

export type DiaryTier = z.infer<typeof DiaryTier>;

export const CombatAchievementTier = z.enum([
  'None',
  'Easy',
  'Medium',
  'Hard',
  'Elite',
  'Master',
  'Grandmaster',
]);

export type CombatAchievementTier = z.infer<typeof CombatAchievementTier>;

export const combatAchievementTierPoints = {
  Easy: 1,
  Medium: 2,
  Hard: 3,
  Elite: 4,
  Master: 5,
  Grandmaster: 6,
} satisfies Record<Exclude<CombatAchievementTier, 'None'>, number>;

export const maximumSkillLevel = 99;

export const skillsCount = Skill.options.length;

export const minimumTotalLevel = skillsCount + 9; // Hitpoints starts at 10

export const maximumTotalLevel = skillsCount * maximumSkillLevel;

/**
 * A complete list of collection log item names, as found on OSRSWiki.
 *
 * https://oldschool.runescape.wiki/?title=Module:Collection_log/data.json&action=raw&ctype=application%2Fjson
 */
export const CollectionLogItemName = z.enum([
  'Dragon spear',
  'Shield left half',
  'Ranger boots',
  'Wizard boots',
  'Robin hood hat',
  'Black platebody (t)',
  'Black platelegs (t)',
  'Black full helm (t)',
  'Black kiteshield (t)',
  'Black platebody (g)',
  'Black platelegs (g)',
  'Black full helm (g)',
  'Black kiteshield (g)',
  'Adamant platebody (t)',
  'Adamant platelegs (t)',
  'Adamant kiteshield (t)',
  'Adamant full helm (t)',
  'Adamant platebody (g)',
  'Adamant platelegs (g)',
  'Adamant kiteshield (g)',
  'Adamant full helm (g)',
  'Rune platebody (g)',
  'Rune platelegs (g)',
  'Rune full helm (g)',
  'Rune kiteshield (g)',
  'Rune platebody (t)',
  'Rune platelegs (t)',
  'Rune full helm (t)',
  'Rune kiteshield (t)',
  'Highwayman mask',
  'Blue beret',
  'Black beret',
  'White beret',
  'Tan cavalier',
  'Dark cavalier',
  'Black cavalier',
  'Red headband',
  'Black headband',
  'Brown headband',
  "Pirate's hat",
  'Zamorak platebody',
  'Zamorak platelegs',
  'Zamorak full helm',
  'Zamorak kiteshield',
  'Saradomin platebody',
  'Saradomin platelegs',
  'Saradomin full helm',
  'Saradomin kiteshield',
  'Guthix platebody',
  'Guthix platelegs',
  'Guthix full helm',
  'Guthix kiteshield',
  'Chompy bird hat',
  'Agility arena ticket',
  "Pirate's hook",
  'Mime mask',
  'Mime top',
  'Mime legs',
  'Mime gloves',
  'Mime boots',
  'Dragon chainbody',
  'Fine cloth',
  'Black plateskirt (t)',
  'Black plateskirt (g)',
  'Adamant plateskirt (t)',
  'Adamant plateskirt (g)',
  'Rune plateskirt (g)',
  'Rune plateskirt (t)',
  'Zamorak plateskirt',
  'Saradomin plateskirt',
  'Guthix plateskirt',
  'Gilded platebody',
  'Gilded platelegs',
  'Gilded plateskirt',
  'Gilded full helm',
  'Gilded kiteshield',
  'Saradomin page 1',
  'Saradomin page 2',
  'Saradomin page 3',
  'Saradomin page 4',
  'Zamorak page 1',
  'Zamorak page 2',
  'Zamorak page 3',
  'Zamorak page 4',
  'Guthix page 1',
  'Guthix page 2',
  'Guthix page 3',
  'Guthix page 4',
  'Decorative sword',
  'Decorative armour',
  'Decorative helm',
  'Decorative shield',
  'Mystic hat (dark)',
  'Mystic robe top (dark)',
  'Mystic robe bottom (dark)',
  'Mystic gloves (dark)',
  'Mystic boots (dark)',
  'Mystic hat (light)',
  'Mystic robe top (light)',
  'Mystic robe bottom (light)',
  'Mystic gloves (light)',
  'Mystic boots (light)',
  'Bronze boots',
  'Iron boots',
  'Steel boots',
  'Black boots',
  'Mithril boots',
  'Adamant boots',
  'Rune boots',
  'Abyssal whip',
  'Granite maul',
  'Crystal weapon seed',
  'Castlewars hood',
  'Castlewars cloak',
  "Ahrim's hood",
  "Ahrim's staff",
  "Ahrim's robetop",
  "Ahrim's robeskirt",
  "Dharok's helm",
  "Dharok's greataxe",
  "Dharok's platebody",
  "Dharok's platelegs",
  "Guthan's helm",
  "Guthan's warspear",
  "Guthan's platebody",
  "Guthan's chainskirt",
  "Karil's coif",
  "Karil's crossbow",
  "Karil's leathertop",
  "Karil's leatherskirt",
  'Bolt rack',
  "Torag's helm",
  "Torag's hammers",
  "Torag's platebody",
  "Torag's platelegs",
  "Verac's helm",
  "Verac's flail",
  "Verac's brassard",
  "Verac's plateskirt",
  'Rogue top',
  'Rogue mask',
  'Rogue trousers',
  'Rogue gloves',
  'Rogue boots',
  'Lederhosen top',
  'Lederhosen shorts',
  'Lederhosen hat',
  'Frog token',
  'Toktz-xil-ul',
  'Toktz-xil-ak',
  'Toktz-ket-xil',
  'Toktz-xil-ek',
  'Toktz-mej-tal',
  'Tzhaar-ket-om',
  'Mud battlestaff',
  'Obsidian cape',
  'Fire cape',
  'Uncut onyx',
  'Onyx',
  'Camo top',
  'Camo bottoms',
  'Camo helmet',
  'Mudskipper hat',
  'Flippers',
  'Seercull',
  'Seers ring',
  'Archers ring',
  'Warrior ring',
  'Berserker ring',
  'Dragon axe',
  'Earth warrior champion scroll',
  'Ghoul champion scroll',
  'Giant champion scroll',
  'Goblin champion scroll',
  'Hobgoblin champion scroll',
  'Imp champion scroll',
  'Jogre champion scroll',
  'Lesser demon champion scroll',
  'Skeleton champion scroll',
  'Zombie champion scroll',
  'Granite legs',
  "Mage's book",
  'Beginner wand',
  'Apprentice wand',
  'Teacher wand',
  'Master wand',
  'Infinity top',
  'Infinity hat',
  'Infinity boots',
  'Infinity gloves',
  'Infinity bottoms',
  'Bones to peaches',
  'Dragon 2h sword',
  'Red boater',
  'Orange boater',
  'Green boater',
  'Blue boater',
  'Black boater',
  'Red firelighter',
  'Green firelighter',
  'Blue firelighter',
  'Black shield (h1)',
  'Adamant shield (h1)',
  'Rune shield (h1)',
  'Black shield (h2)',
  'Adamant shield (h2)',
  'Rune shield (h2)',
  'Black shield (h3)',
  'Adamant shield (h3)',
  'Rune shield (h3)',
  'Black shield (h4)',
  'Adamant shield (h4)',
  'Rune shield (h4)',
  'Black shield (h5)',
  'Adamant shield (h5)',
  'Rune shield (h5)',
  'Studded body (g)',
  'Studded body (t)',
  'Studded chaps (g)',
  'Studded chaps (t)',
  "Green d'hide body (g)",
  "Green d'hide body (t)",
  "Blue d'hide body (g)",
  "Blue d'hide body (t)",
  "Green d'hide chaps (g)",
  "Green d'hide chaps (t)",
  "Blue d'hide chaps (g)",
  "Blue d'hide chaps (t)",
  'Blue skirt (g)',
  'Blue skirt (t)',
  'Blue wizard robe (g)',
  'Blue wizard robe (t)',
  'Blue wizard hat (g)',
  'Blue wizard hat (t)',
  'Enchanted robe',
  'Enchanted top',
  'Enchanted hat',
  'Mole claw',
  'Mole skin',
  'Fresh crab claw',
  'Fresh crab shell',
  'Zombie shirt',
  'Zombie trousers',
  'Zombie mask',
  'Zombie gloves',
  'Zombie boots',
  'Crawling hand',
  'Cockatrice head',
  'Basilisk head',
  'Kurask head',
  'Abyssal head',
  'Kbd heads',
  'Kq head',
  'Big bass',
  'Big swordfish',
  'Big shark',
  'Void knight top',
  'Void knight robe',
  'Void knight mace',
  'Void knight gloves',
  'Bronze defender',
  'Iron defender',
  'Steel defender',
  'Black defender',
  'Mithril defender',
  'Adamant defender',
  'Rune defender',
  'Black mask (10)',
  'Rum',
  'Blue naval shirt',
  'Green naval shirt',
  'Red naval shirt',
  'Brown naval shirt',
  'Black naval shirt',
  'Purple naval shirt',
  'Grey naval shirt',
  'Blue tricorn hat',
  'Green tricorn hat',
  'Red tricorn hat',
  'Brown tricorn hat',
  'Black tricorn hat',
  'Purple tricorn hat',
  'Grey tricorn hat',
  'Cutthroat flag',
  'Gilded smile flag',
  'Bronze fist flag',
  'Lucky shot flag',
  'Treasure flag',
  'Phasmatys flag',
  'The stuff',
  'Blue navy slacks',
  'Green navy slacks',
  'Red navy slacks',
  'Brown navy slacks',
  'Black navy slacks',
  'Purple navy slacks',
  'Grey navy slacks',
  'Right skull half',
  'Left skull half',
  'Top of sceptre',
  'Bottom of sceptre',
  'Grand seed pod',
  'Gnome scarf',
  'Gnome goggles',
  'Mint cake',
  'Willow comp bow',
  'Yew comp bow',
  'Magic comp bow',
  'Rune helm (h1)',
  'Rune helm (h2)',
  'Rune helm (h3)',
  'Rune helm (h4)',
  'Rune helm (h5)',
  'Adamant helm (h1)',
  'Adamant helm (h2)',
  'Adamant helm (h3)',
  'Adamant helm (h4)',
  'Adamant helm (h5)',
  'Black helm (h1)',
  'Black helm (h2)',
  'Black helm (h3)',
  'Black helm (h4)',
  'Black helm (h5)',
  "Bob's red shirt",
  "Bob's blue shirt",
  "Bob's green shirt",
  "Bob's black shirt",
  "Bob's purple shirt",
  'Purple firelighter',
  'White firelighter',
  '3rd age range top',
  '3rd age range legs',
  '3rd age range coif',
  '3rd age vambraces',
  '3rd age robe top',
  '3rd age robe',
  '3rd age mage hat',
  '3rd age amulet',
  '3rd age platelegs',
  '3rd age platebody',
  '3rd age full helmet',
  '3rd age kiteshield',
  'Amulet of glory (t4)',
  'Strength amulet (t)',
  'Amulet of magic (t)',
  'Zamorak bracers',
  "Zamorak d'hide body",
  'Zamorak chaps',
  'Zamorak coif',
  'Guthix bracers',
  "Guthix d'hide body",
  'Guthix chaps',
  'Guthix coif',
  'Saradomin bracers',
  "Saradomin d'hide body",
  'Saradomin chaps',
  'Saradomin coif',
  'A powdered wig',
  'Flared trousers',
  'Pantaloons',
  'Sleeping cap',
  'Black elegant shirt',
  'Black elegant legs',
  'Red elegant shirt',
  'Red elegant legs',
  'Blue elegant shirt',
  'Blue elegant legs',
  'Green elegant shirt',
  'Green elegant legs',
  'Purple elegant shirt',
  'Purple elegant legs',
  'White elegant blouse',
  'White elegant skirt',
  'Red elegant blouse',
  'Red elegant skirt',
  'Blue elegant blouse',
  'Blue elegant skirt',
  'Green elegant blouse',
  'Green elegant skirt',
  'Purple elegant blouse',
  'Purple elegant skirt',
  'Saradomin crozier',
  'Guthix crozier',
  'Zamorak crozier',
  'Saradomin cloak',
  'Guthix cloak',
  'Zamorak cloak',
  'Saradomin mitre',
  'Guthix mitre',
  'Zamorak mitre',
  'Saradomin robe top',
  'Zamorak robe top',
  'Guthix robe top',
  'Saradomin robe legs',
  'Guthix robe legs',
  'Zamorak robe legs',
  'Saradomin stole',
  'Guthix stole',
  'Zamorak stole',
  'Purple sweets',
  'Healer hat',
  'Fighter hat',
  'Runner hat',
  'Ranger hat',
  'Fighter torso',
  'Runner boots',
  'Penance gloves',
  'Penance skirt',
  'Granite body',
  'Granite helm',
  'Lumberjack boots',
  'Lumberjack top',
  'Lumberjack legs',
  'Lumberjack hat',
  'Long bone',
  'Curved bone',
  'Brine sabre',
  'Dark bow',
  'Draconic visage',
  'Dragon full helm',
  'Chewed bones',
  'Ancient page',
  'Void mage helm',
  'Void ranger helm',
  'Void melee helm',
  'Void seal(8)',
  'Armadyl crossbow',
  'Steam battlestaff',
  'Staff of the dead',
  'Armadyl hilt',
  'Bandos hilt',
  'Saradomin hilt',
  'Zamorak hilt',
  'Godsword shard 1',
  'Godsword shard 2',
  'Godsword shard 3',
  'Zamorakian spear',
  'Armadyl helmet',
  'Armadyl chestplate',
  'Armadyl chainskirt',
  'Bandos chestplate',
  'Bandos tassets',
  'Bandos boots',
  'Saradomin sword',
  'Dragon boots',
  'Mark of grace',
  'Graceful hood',
  'Graceful cape',
  'Graceful top',
  'Graceful legs',
  'Graceful gloves',
  'Graceful boots',
  'Saradomin banner',
  'Zamorak banner',
  'Leaf-bladed sword',
  'Trident of the seas (full)',
  'Uncharged trident',
  'Dragon pickaxe',
  'Odium shard 1',
  'Odium shard 2',
  'Odium shard 3',
  'Malediction shard 1',
  'Malediction shard 2',
  'Malediction shard 3',
  'Ecumenical key',
  'Fedora',
  'Pet chaos elemental',
  'Smoke battlestaff',
  'Occult necklace',
  'Kraken tentacle',
  'Jar of dirt',
  'Prospector helmet',
  'Prospector jacket',
  'Prospector legs',
  'Prospector boots',
  'Ancient robe top',
  'Ancient robe legs',
  'Ancient cloak',
  'Ancient crozier',
  'Ancient stole',
  'Ancient mitre',
  'Bronze platebody (g)',
  'Bronze platelegs (g)',
  'Bronze plateskirt (g)',
  'Bronze full helm (g)',
  'Bronze kiteshield (g)',
  'Bronze platebody (t)',
  'Bronze platelegs (t)',
  'Bronze plateskirt (t)',
  'Bronze full helm (t)',
  'Bronze kiteshield (t)',
  'Iron platebody (t)',
  'Iron platelegs (t)',
  'Iron plateskirt (t)',
  'Iron full helm (t)',
  'Iron kiteshield (t)',
  'Iron platebody (g)',
  'Iron platelegs (g)',
  'Iron plateskirt (g)',
  'Iron full helm (g)',
  'Iron kiteshield (g)',
  'Beanie',
  'Red beret',
  'Imp mask',
  'Goblin mask',
  'Armadyl robe top',
  'Armadyl robe legs',
  'Armadyl stole',
  'Armadyl mitre',
  'Armadyl cloak',
  'Armadyl crozier',
  'Bandos robe top',
  'Bandos robe legs',
  'Bandos stole',
  'Bandos mitre',
  'Bandos cloak',
  'Bandos crozier',
  'Mithril platebody (g)',
  'Mithril platelegs (g)',
  'Mithril kiteshield (g)',
  'Mithril full helm (g)',
  'Mithril plateskirt (g)',
  'Mithril platebody (t)',
  'Mithril platelegs (t)',
  'Mithril kiteshield (t)',
  'Mithril full helm (t)',
  'Mithril plateskirt (t)',
  'Black pickaxe',
  'White headband',
  'Blue headband',
  'Gold headband',
  'Pink headband',
  'Green headband',
  'Pink boater',
  'Purple boater',
  'White boater',
  'Pink elegant shirt',
  'Pink elegant legs',
  'Crier hat',
  'White cavalier',
  'Red cavalier',
  'Navy cavalier',
  "Red d'hide body (g)",
  "Red d'hide chaps (g)",
  "Red d'hide body (t)",
  "Red d'hide chaps (t)",
  'Briefcase',
  'Sagacious spectacles',
  'Pink elegant blouse',
  'Pink elegant skirt',
  'Gold elegant blouse',
  'Gold elegant skirt',
  'Gold elegant shirt',
  'Gold elegant legs',
  'Musketeer hat',
  'Monocle',
  'Big pirate hat',
  'Katana',
  'Leprechaun hat',
  'Cat mask',
  'Bronze dragon mask',
  'Iron dragon mask',
  'Steel dragon mask',
  'Mithril dragon mask',
  'Lava dragon mask',
  'Dragon cane',
  'Black cane',
  'Adamant cane',
  'Rune cane',
  "Black d'hide body (g)",
  "Black d'hide chaps (g)",
  "Black d'hide body (t)",
  "Black d'hide chaps (t)",
  'Gilded scimitar',
  'Gilded boots',
  'Royal gown top',
  'Royal gown bottom',
  'Royal crown',
  'Nardah teleport',
  'Digsite teleport',
  'Feldip hills teleport',
  'Lunar isle teleport',
  "Mort'ton teleport",
  'Pest control teleport',
  'Piscatoris teleport',
  'Tai bwo wannai teleport',
  'Iorwerth camp teleport',
  "Mos le'harmless teleport",
  '3rd age wand',
  '3rd age bow',
  '3rd age longsword',
  'Penguin mask',
  'Afro',
  'Top hat',
  '3rd age cloak',
  'Royal sceptre',
  'Musketeer tabard',
  'Musketeer pants',
  'Black skirt (g)',
  'Black skirt (t)',
  'Black wizard robe (g)',
  'Black wizard robe (t)',
  'Black wizard hat (g)',
  'Black wizard hat (t)',
  'Ancient platebody',
  'Ancient platelegs',
  'Ancient plateskirt',
  'Ancient full helm',
  'Ancient kiteshield',
  'Armadyl platebody',
  'Armadyl platelegs',
  'Armadyl plateskirt',
  'Armadyl full helm',
  'Armadyl kiteshield',
  'Bandos platebody',
  'Bandos platelegs',
  'Bandos plateskirt',
  'Bandos full helm',
  'Bandos kiteshield',
  'Ancient bracers',
  "Ancient d'hide body",
  'Ancient chaps',
  'Ancient coif',
  'Bandos bracers',
  "Bandos d'hide body",
  'Bandos chaps',
  'Bandos coif',
  'Armadyl bracers',
  "Armadyl d'hide body",
  'Armadyl chaps',
  'Armadyl coif',
  'Explorer backpack',
  'Pith helmet',
  'Green dragon mask',
  'Blue dragon mask',
  'Red dragon mask',
  'Black dragon mask',
  'Fury ornament kit',
  'Dark infinity colour kit',
  'Light infinity colour kit',
  'Dragon sq shield ornament kit',
  'Dragon chainbody ornament kit',
  'Dragon legs/skirt ornament kit',
  'Dragon full helm ornament kit',
  'Deerstalker',
  "Rangers' tunic",
  'Holy sandals',
  'Ring of the gods',
  'Tyrannical ring',
  'Treasonous ring',
  'Bandos page 1',
  'Bandos page 2',
  'Bandos page 3',
  'Bandos page 4',
  'Armadyl page 1',
  'Armadyl page 2',
  'Armadyl page 3',
  'Armadyl page 4',
  'Ancient page 1',
  'Ancient page 2',
  'Ancient page 3',
  'Ancient page 4',
  'Saradomin halo',
  'Zamorak halo',
  'Guthix halo',
  'Lumberyard teleport',
  'Pet dagannoth supreme',
  'Pet dagannoth prime',
  'Pet dagannoth rex',
  'Baby mole',
  'Kalphite princess',
  'Pet smoke devil',
  "Pet kree'arra",
  'Pet general graardor',
  'Pet zilyana',
  "Pet k'ril tsutsaroth",
  'Prince black dragon',
  'Pet kraken',
  'Pet penance queen',
  'Blue dark bow paint',
  'Green dark bow paint',
  'Yellow dark bow paint',
  'White dark bow paint',
  'Frozen whip mix',
  'Volcanic whip mix',
  'Steam staff upgrade kit',
  'Dragon pickaxe upgrade kit',
  'Ward upgrade kit',
  'Pet dark core',
  'Elysian sigil',
  'Spectral sigil',
  'Arcane sigil',
  'Spirit shield',
  'Holy elixir',
  'Granite clamp',
  'Amulet of the damned (full)',
  'Jar of sand',
  'Pet snakeling',
  'Tanzanite fang',
  'Serpentine visage',
  'Magic fang',
  "Zulrah's scales",
  'Jar of swamp',
  'Zul-andra teleport',
  'Dragon defender',
  'Chompy chick',
  'Elite void top',
  'Elite void robe',
  'Venenatis spiderling',
  'Callisto cub',
  "Vet'ion jr.",
  "Scorpia's offspring",
  'Tanzanite mutagen',
  'Magma mutagen',
  'Tzrek-jad',
  'Herb sack',
  'Eternal crystal',
  'Pegasian crystal',
  'Primordial crystal',
  'Smouldering stone',
  'Jar of souls',
  'Hellpuppy',
  'Key master teleport',
  "Saradomin's light",
  'Angler hat',
  'Angler top',
  'Angler waders',
  'Angler boots',
  'Abyssal orphan',
  'Abyssal dagger',
  'Bludgeon spine',
  'Bludgeon claw',
  'Bludgeon axon',
  'Jar of miasma',
  'Heron',
  'Rock golem',
  'Beaver',
  'Baby chinchompa',
  "Gricoller's can",
  'Shayzien gloves (1)',
  'Shayzien boots (1)',
  'Shayzien helm (1)',
  'Shayzien greaves (1)',
  'Shayzien platebody (1)',
  'Shayzien gloves (2)',
  'Shayzien boots (2)',
  'Shayzien helm (2)',
  'Shayzien greaves (2)',
  'Shayzien platebody (2)',
  'Shayzien gloves (3)',
  'Shayzien boots (3)',
  'Shayzien helm (3)',
  'Shayzien greaves (3)',
  'Shayzien platebody (3)',
  'Shayzien gloves (4)',
  'Shayzien boots (4)',
  'Shayzien helm (4)',
  'Shayzien greaves (4)',
  'Shayzien platebody (4)',
  'Shayzien gloves (5)',
  'Shayzien boots (5)',
  'Shayzien helm (5)',
  'Shayzien greaves (5)',
  'Shayzien body (5)',
  "Xeric's talisman (inert)",
  'Dragon warhammer',
  'Seed box',
  "Farmer's boro trousers",
  "Farmer's jacket",
  "Farmer's boots",
  "Farmer's strawhat",
  'Dragon claws',
  'Zenyte shard',
  'Light frame',
  'Heavy frame',
  'Ballista limbs',
  'Ballista spring',
  'Monkey tail',
  'Ancient shard',
  'Dark totem base',
  'Dark totem middle',
  'Dark totem top',
  'Dark totem',
  'Jar of darkness',
  'Amulet of eternal glory',
  'Left eye patch',
  'Bloodhound',
  'Zombie head',
  'Cyclops head',
  'Nunchaku',
  "Ancient d'hide boots",
  "Bandos d'hide boots",
  "Guthix d'hide boots",
  "Armadyl d'hide boots",
  "Saradomin d'hide boots",
  "Zamorak d'hide boots",
  'Arceuus scarf',
  'Hosidius scarf',
  'Lovakengj scarf',
  'Piscarilius scarf',
  'Shayzien scarf',
  'Dark tuxedo jacket',
  'Dark tuxedo cuffs',
  'Dark trousers',
  'Dark tuxedo shoes',
  'Dark bow tie',
  'Light tuxedo jacket',
  'Light tuxedo cuffs',
  'Light trousers',
  'Light tuxedo shoes',
  'Light bow tie',
  "Blacksmith's helm",
  'Bucket helm',
  'Ranger gloves',
  'Holy wraps',
  'Dragon scimitar ornament kit',
  'Ring of nature',
  'Fancy tiara',
  '3rd age axe',
  '3rd age pickaxe',
  'Ring of coins',
  'Lesser demon mask',
  'Greater demon mask',
  'Black demon mask',
  'Old demon mask',
  'Jungle demon mask',
  'Samurai kasa',
  'Samurai shirt',
  'Samurai gloves',
  'Samurai greaves',
  'Samurai boots',
  'Obsidian cape (r)',
  'Half moon spectacles',
  'Ale of the gods',
  'Bucket helm (g)',
  'Torture ornament kit',
  'Occult ornament kit',
  'Armadyl godsword ornament kit',
  'Bandos godsword ornament kit',
  'Saradomin godsword ornament kit',
  'Zamorak godsword ornament kit',
  "Mummy's head",
  "Mummy's body",
  "Mummy's hands",
  "Mummy's legs",
  "Mummy's feet",
  'Ankou mask',
  'Ankou top',
  'Ankou gloves',
  "Ankou's leggings",
  'Ankou socks',
  'Bowl wig',
  'Arceuus hood',
  'Hosidius hood',
  'Lovakengj hood',
  'Piscarilius hood',
  'Shayzien hood',
  'Hood of darkness',
  'Robe top of darkness',
  'Gloves of darkness',
  'Robe bottom of darkness',
  'Boots of darkness',
  'Dragon defender ornament kit',
  'Gilded med helm',
  'Gilded chainbody',
  'Gilded sq shield',
  'Gilded 2h sword',
  'Gilded spear',
  'Gilded hasta',
  'Wooden shield (g)',
  'Steel platebody (g)',
  'Steel platelegs (g)',
  'Steel plateskirt (g)',
  'Steel full helm (g)',
  'Steel kiteshield (g)',
  'Steel platebody (t)',
  'Steel platelegs (t)',
  'Steel plateskirt (t)',
  'Steel full helm (t)',
  'Steel kiteshield (t)',
  "Monk's robe top (g)",
  "Monk's robe (g)",
  "Golden chef's hat",
  'Golden apron',
  'Team cape zero',
  'Team cape x',
  'Team cape i',
  'Holy blessing',
  'Unholy blessing',
  'Peaceful blessing',
  'Honourable blessing',
  'War blessing',
  'Ancient blessing',
  'Charge dragonstone jewellery scroll',
  'Crier coat',
  'Crier bell',
  'Black leprechaun hat',
  'Arceuus banner',
  'Hosidius banner',
  'Lovakengj banner',
  'Piscarilius banner',
  'Shayzien banner',
  'Black unicorn mask',
  'White unicorn mask',
  'Cabbage round shield',
  'Gnomish firelighter',
  'Evil chicken feet',
  'Evil chicken wings',
  'Evil chicken head',
  'Evil chicken legs',
  'Elder chaos top',
  'Elder chaos robe',
  'Stale baguette',
  'Elder chaos hood',
  'Giant squirrel',
  'Tangleroot',
  'Rocky',
  'Rift guardian',
  'Phoenix',
  'Pyromancer garb',
  'Pyromancer robe',
  'Pyromancer hood',
  'Pyromancer boots',
  'Warm gloves',
  'Tome of fire (empty)',
  'Burnt page',
  'Bruma torch',
  'Imbued heart',
  'Leaf-bladed battleaxe',
  'Mist battlestaff',
  'Dust battlestaff',
  'Giant key',
  'Hill giant club',
  'Dragon thrownaxe',
  'Olmlet',
  'Twisted bow',
  'Twisted buckler',
  'Elder maul',
  'Dragon sword',
  'Dragon hunter crossbow',
  "Dinh's bulwark",
  'Ancestral hat',
  'Ancestral robe top',
  'Ancestral robe bottom',
  'Dark relic',
  'Dragon harpoon',
  'Dexterous prayer scroll',
  'Kodai insignia',
  'Torn prayer scroll',
  'Arcane prayer scroll',
  'Lava staff upgrade kit',
  'Eternal gem',
  'Skotos',
  'Dark claw',
  'Jal-nib-rek',
  'Infernal cape',
  'Obsidian helmet',
  'Obsidian platebody',
  'Obsidian platelegs',
  'Mining gloves',
  'Superior mining gloves',
  'Master scroll book (empty)',
  'Expert mining gloves',
  "Champion's cape",
  'Herbi',
  'Volcanic mine teleport',
  'Wyvern visage',
  'Granite boots',
  'Granite longsword',
  'Merfolk trident',
  'Scribbled note',
  'Partial note',
  'Ancient note',
  'Ancient writings',
  'Experimental note',
  'Paragraph of text',
  'Musty smelling note',
  'Hastily scrawled note',
  'Old writing',
  'Short note',
  'Ash covered tome',
  'Granite dust',
  'Black tourmaline core',
  'Granite gloves',
  'Granite ring',
  'Granite hammer',
  'Jar of stone',
  'Noon',
  'Revenant cave teleport',
  'Ancient crystal',
  'Ancient emblem',
  'Ancient totem',
  'Ancient statuette',
  'Bracelet of ethereum (uncharged)',
  'Revenant ether',
  'Shaman mask',
  "Vorkath's head",
  'Dragon limbs',
  'Vorki',
  'Skeletal visage',
  'Dragon metal slice',
  'Dragon metal lump',
  'Jar of decay',
  'Dragonbone necklace',
  'Dragon boots ornament kit',
  'Dragon platebody ornament kit',
  'Dragon kiteshield ornament kit',
  'Anguish ornament kit',
  'Ancient medallion',
  'Ancient effigy',
  'Ancient relic',
  'Ghrazi rapier',
  'Justiciar faceguard',
  'Justiciar chestguard',
  'Justiciar legguards',
  "Bryophyta's essence",
  'Mossy key',
  'Metamorphic dust',
  "Xeric's guard",
  "Xeric's warrior",
  "Xeric's sentinel",
  "Xeric's general",
  "Xeric's champion",
  'Vial of blood',
  "Lil' zik",
  'Avernic defender hilt',
  'Sanguinesti staff (uncharged)',
  'Scythe of vitur (uncharged)',
  'Sinhaza shroud tier 1',
  'Sinhaza shroud tier 2',
  'Sinhaza shroud tier 3',
  'Sinhaza shroud tier 4',
  'Sinhaza shroud tier 5',
  "Viggora's chainmace (u)",
  "Craw's bow (u)",
  "Thammaron's sceptre (u)",
  'Amulet of avarice',
  'Ikkle hydra',
  'Dragon knife',
  'Fish sack',
  'Golden tench',
  'Pearl barbarian rod',
  'Pearl fly fishing rod',
  'Pearl fishing rod',
  'Hespori seed',
  'Attas seed',
  'Iasor seed',
  'Kronos seed',
  "Drake's claw",
  "Drake's tooth",
  'Broken dragon hasta',
  "Hydra's claw",
  "Hydra's heart",
  "Hydra's fang",
  "Hydra's eye",
  'Hydra leather',
  'Hydra tail',
  'Bottomless compost bucket',
  'Mystic hat (dusk)',
  'Mystic robe top (dusk)',
  'Mystic robe bottom (dusk)',
  'Mystic gloves (dusk)',
  'Mystic boots (dusk)',
  'Jar of chemicals',
  'Alchemical hydra heads',
  'Ring of 3rd age',
  "Guthix d'hide shield",
  "Saradomin d'hide shield",
  "Zamorak d'hide shield",
  "Ancient d'hide shield",
  "Armadyl d'hide shield",
  "Bandos d'hide shield",
  'Dual sai',
  'Rune platebody (h1)',
  'Rune platebody (h2)',
  'Rune platebody (h3)',
  'Rune platebody (h4)',
  'Rune platebody (h5)',
  'Thieving bag',
  'Rune defender ornament kit',
  'Tzhaar-ket-om ornament kit',
  'Berserker necklace ornament kit',
  '3rd age plateskirt',
  'Fremennik kilt',
  "Rangers' tights",
  'Giant boot',
  "Uri's hat",
  'Gilded coif',
  "Gilded d'hide vambraces",
  "Gilded d'hide body",
  "Gilded d'hide chaps",
  'Adamant dragon mask',
  'Rune dragon mask',
  'Gilded pickaxe',
  'Gilded axe',
  'Gilded spade',
  'Mole slippers',
  'Frog slippers',
  'Bear feet',
  'Demon feet',
  'Jester cape',
  'Shoulder parrot',
  "Monk's robe top (t)",
  "Monk's robe (t)",
  'Amulet of defence (t)',
  'Sandwich lady hat',
  'Sandwich lady top',
  'Sandwich lady bottom',
  'Rune scimitar ornament kit (guthix)',
  'Rune scimitar ornament kit (saradomin)',
  'Rune scimitar ornament kit (zamorak)',
  '3rd age druidic robe top',
  '3rd age druidic robe bottoms',
  '3rd age druidic staff',
  '3rd age druidic cloak',
  'Tormented ornament kit',
  'Cape of skulls',
  'Amulet of power (t)',
  'Rain bow',
  'Ham joint',
  'Staff of bob the cat',
  'Black platebody (h1)',
  'Black platebody (h2)',
  'Black platebody (h3)',
  'Black platebody (h4)',
  'Black platebody (h5)',
  'Leather body (g)',
  'Leather chaps (g)',
  'Spiked manacles',
  'Adamant platebody (h1)',
  'Adamant platebody (h2)',
  'Adamant platebody (h3)',
  'Adamant platebody (h4)',
  'Adamant platebody (h5)',
  'Wolf mask',
  'Wolf cloak',
  'Climbing boots (g)',
  'Sraracha',
  'Giant egg sac(full)',
  'Mask of ranul',
  'Jar of eyes',
  'Sarachnis cudgel',
  'Youngllef',
  'Smolcano',
  'Gauntlet cape',
  'Zalcano shard',
  'Elven signet',
  'Crystal tool seed',
  'Crystal armour seed',
  'Enhanced crystal teleport seed',
  'Crystal grail',
  'Dragonstone full helm',
  'Dragonstone platebody',
  'Dragonstone platelegs',
  'Dragonstone boots',
  'Dragonstone gauntlets',
  "Deadman's chest",
  "Deadman's legs",
  "Deadman's cape",
  'Armadyl halo',
  'Bandos halo',
  'Seren halo',
  'Ancient halo',
  'Brassica halo',
  "Victor's cape (1)",
  "Victor's cape (10)",
  "Victor's cape (50)",
  "Victor's cape (100)",
  "Victor's cape (500)",
  'Guthixian icon',
  'Swift blade',
  'Ornate maul handle',
  'Basilisk jaw',
  "Dagon'hai hat",
  "Dagon'hai robe top",
  "Dagon'hai robe bottom",
  "Inquisitor's mace",
  "Inquisitor's great helm",
  "Inquisitor's hauberk",
  "Inquisitor's plateskirt",
  'Nightmare staff',
  'Little nightmare',
  'Jar of dreams',
  'Harmonised orb',
  'Volatile orb',
  'Eldritch orb',
  "Victor's cape (1000)",
  'Twisted ancestral colour kit',
  'Hallowed mark',
  'Hallowed token',
  'Hallowed grapple',
  'Hallowed focus',
  'Hallowed symbol',
  'Hallowed hammer',
  'Dark dye',
  'Hallowed ring',
  'Dark acorn',
  'Strange old lockpick (full)',
  'Mysterious page',
  'Blood shard',
  'Ring of endurance (uncharged)',
  'Karamjan monkey',
  'Zombie monkey',
  'Maniacal monkey',
  'Skeleton monkey',
  'Kruk jr',
  'Princely monkey',
  'Golden armadyl special attack',
  'Golden bandos special attack',
  'Golden saradomin special attack',
  'Golden zamorak special attack',
  "Carpenter's helmet",
  "Carpenter's shirt",
  "Carpenter's trousers",
  "Carpenter's boots",
  "Amy's saw",
  'Supply crate',
  'Hosidius blueprints',
  "Beekeeper's hat",
  "Beekeeper's top",
  "Beekeeper's legs",
  "Beekeeper's gloves",
  "Beekeeper's boots",
  'Decorative boots',
  'Decorative full helm',
  'Ectoplasmator',
  'Soul cape',
  "Lil' creator",
  "Zealot's robe top",
  "Zealot's robe bottom",
  "Zealot's helm",
  "Zealot's boots",
  'Bronze locks',
  'Steel locks',
  'Black locks',
  'Silver locks',
  'Gold locks',
  "Tree wizards' journal",
  'Bloody notes',
  'Jar of spirits',
  'Jar of smoke',
  'Celestial ring (uncharged)',
  'Star fragment',
  'Big harpoonfish',
  'Tome of water (empty)',
  'Soaked page',
  'Tackle box',
  'Fish barrel',
  'Spirit flakes',
  'Spirit angler headband',
  'Spirit angler top',
  'Spirit angler waders',
  'Spirit angler boots',
  'Tiny tempor',
  'Large water container',
  'Tea flask',
  'Plain satchel',
  'Green satchel',
  'Red satchel',
  'Black satchel',
  'Gold satchel',
  'Rune satchel',
  'Unsired',
  'Coal bag',
  'Gem bag',
  'Plank sack',
  'Flamtaer bag',
  'Barronite head',
  'Barronite handle',
  'Barronite guard',
  'Barronite mace',
  'Imcando hammer',
  'Ancient globe',
  'Ancient ledger',
  'Ancient astroscope',
  'Ancient treatise',
  'Ancient carcanet',
  'Holy ornament kit',
  'Sanguine ornament kit',
  'Sanguine dust',
  'Slepey tablet',
  'Parasitic egg',
  'Orange egg sac',
  'Blue egg sac',
  'Enhanced crystal weapon seed',
  'Lightbearer',
  "Elidinis' ward",
  "Osmumten's fang",
  'Ancient ceremonial top',
  'Ancient ceremonial legs',
  'Ancient ceremonial mask',
  'Ancient ceremonial gloves',
  'Ancient ceremonial boots',
  'Nihil shard',
  'Zaryte vambraces',
  'Virtus mask',
  'Virtus robe top',
  'Virtus robe bottom',
  'Nexling',
  'Ancient hilt',
  'Nihil horn',
  'Torva full helm (damaged)',
  'Torva platebody (damaged)',
  'Torva platelegs (damaged)',
  'Abyssal pearls',
  'Catalytic talisman',
  'Abyssal green dye',
  'Abyssal blue dye',
  'Abyssal red dye',
  'Abyssal needle',
  'Ring of the elements',
  "Guardian's eye",
  'Abyssal lantern',
  'Hat of the eye',
  'Robe top of the eye',
  'Robe bottoms of the eye',
  'Boots of the eye',
  'Abyssal protector',
  'Intricate pouch',
  'Tarnished locket',
  'Lost bag',
  "Pharaoh's sceptre (uncharged)",
  'Double ammo mould',
  "Kovac's grog",
  'Smithing catalyst',
  'Ore pack',
  'Colossal blade',
  'Smiths tunic',
  'Smiths trousers',
  'Smiths boots',
  'Smiths gloves',
  'Masori mask',
  'Masori body',
  'Masori chaps',
  'Cursed phalanx',
  'Menaphite ornament kit',
  "Icthlarin's shroud (tier 1)",
  "Icthlarin's shroud (tier 2)",
  "Icthlarin's shroud (tier 3)",
  "Icthlarin's shroud (tier 4)",
  "Icthlarin's shroud (tier 5)",
  "Tumeken's shadow (uncharged)",
  'Thread of elidinis',
  'Breach of the scarab',
  'Eye of the corruptor',
  'Jewel of the sun',
  'Cache of runes',
  "Tumeken's guardian",
  'Masori crafting kit',
  'Remnant of akkha',
  'Remnant of ba-ba',
  'Remnant of kephri',
  'Remnant of zebak',
  'Ancient remnant',
  'Muphin',
  'Venator shard',
  'Ancient essence',
  'Frozen cache',
  'Ancient icon',
  'Charged ice',
  'Claws of callisto',
  'Fangs of venenatis',
  "Skull of vet'ion",
  'Voidwaker hilt',
  'Voidwaker blade',
  'Voidwaker gem',
  'Dragon pickaxe (broken)',
  'Funky shaped log',
  'Log basket',
  'Log brace',
  'Clothes pouch blueprint',
  'Forestry top',
  'Forestry legs',
  'Forestry hat',
  'Forestry boots',
  'Felling axe handle',
  'Wisp',
  'Butch',
  'Baron',
  "Lil'viathan",
  'Blood quartz',
  'Ice quartz',
  'Shadow quartz',
  'Smoke quartz',
  'Chromium ingot',
  'Bellator vestige',
  'Magus vestige',
  'Venator vestige',
  'Ultor vestige',
  "Executioner's axe head",
  'Eye of the duke',
  "Siren's staff",
  "Leviathan's lure",
  'Strangled tablet',
  'Sirenic tablet',
  'Scarred tablet',
  'Frozen tablet',
  "Awakener's orb",
  'Warped sceptre (uncharged)',
  'Cape pouch',
  'Pheasant cape',
  'Pheasant boots',
  'Pheasant hat',
  'Pheasant legs',
  'Fox whistle',
  "Twitcher's gloves",
  'Petal garland',
  'Golden pheasant egg',
  'Sturdy beehive parts',
  "Scurrius' spine",
  'Scurry',
  'Broken zombie axe',
  'Tonalztics of ralos (uncharged)',
  'Sunfire splinters',
  'Sunfire fanatic helm',
  'Sunfire fanatic cuirass',
  'Sunfire fanatic chausses',
  'Echo crystal',
  "Dizana's quiver (uncharged)",
  'Smol heredit',
  'Quetzin',
  'Blue moon spear',
  'Atlatl dart',
  'Dual macuahuitl',
  'Eclipse atlatl',
  'Eclipse moon chestplate',
  'Eclipse moon tassets',
  'Eclipse moon helm',
  'Blue moon chestplate',
  'Blue moon tassets',
  'Blue moon helm',
  'Blood moon chestplate',
  'Blood moon tassets',
  'Blood moon helm',
  'Sulphur blades',
  'Guild hunter headwear',
  'Guild hunter top',
  'Guild hunter legs',
  'Guild hunter boots',
  "Huntsman's kit",
  'Teleport anchoring scroll',
  'Brimhaven voucher',
  'Burning claw',
  'Tormented synapse',
  'Guthixian temple teleport',
  'Coagulated venom',
  'Spider cave teleport',
  'Araxyte venom sack',
  'Jar of venom',
  'Araxyte head',
  'Noxious point',
  'Noxious blade',
  'Noxious pommel',
  'Araxyte fang',
  'Aranea boots',
  'Nid',
  'Glacial temotli',
  'Pendant of ates (inert)',
  'Frozen tear',
  'Prescription goggles',
  'Alchemist labcoat',
  'Alchemist pants',
  'Alchemist gloves',
  "Alchemist's amulet",
  'Reagent pouch',
  'Chugging barrel (disassembled)',
  'Colossal wyrm teleport scroll',
  'Calcified acorn',
  'Tome of earth (empty)',
  'Soiled page',
  'Dragon hunter wand',
  'Hueycoatl hide',
  'Huasca seed',
  'Huberte',
  'Moxi',
  'Broken zombie helmet',
  'Bran',
  'Deadeye prayer scroll',
  'Mystic vigour prayer scroll',
  'Ice element staff crown',
  'Fire element staff crown',
  'Giantsoul amulet (uncharged)',
  'Desiccated page',
  'Yami',
  'Chasm teleport scroll',
  'Oathplate helm',
  'Oathplate chest',
  'Oathplate legs',
  'Soulflame horn',
  'Oathplate shards',
  'Rite of vile transference',
  'Forgotten lockbox',
  'Dossier',
  'Barrel of demonic tallow (full)',
  'Jewel of amascut',
  'Steel ring',
  'Minor beginner scroll case',
  'Major beginner scroll case',
  'Minor easy scroll case',
  'Major easy scroll case',
  'Minor medium scroll case',
  'Major medium scroll case',
  'Minor hard scroll case',
  'Major hard scroll case',
  'Minor elite scroll case',
  'Major elite scroll case',
  'Minor master scroll case',
  'Major master scroll case',
  'Mimic scroll case',
  'Dom',
  'Avernic treads',
  'Eye of ayak (uncharged)',
  'Mokhaiotl cloth',
  'Mokhaiotl waystone',
  'Demon tear',
  'Fletching knife',
  'Bow string spool',
  'Ent branch',
  'Greenman mask',
  'Earthbound tecpatl',
  'Antler guard',
  "Alchemist's signet",
  'Broken antler',
  'Helmet of the moon',
]);

export type CollectionLogItemName = z.infer<typeof CollectionLogItemName>;

export const TzHaarCape = z.enum([
  'None',
  ...CollectionLogItemName.extract(['Fire cape', 'Infernal cape']).options,
]);

export type TzHaarCape = z.infer<typeof TzHaarCape>;
